name: Deploy to Staging

on:
  push:
    branches:
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install & Build
        run: |
          corepack enable
          pnpm install
          pnpm build
          cp -r public .next/standalone/
          cp -r .next/static .next/standalone/.next/

      - name: Sync app to droplet via rsync
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USER }}
          key: ${{ secrets.DEPLOY_SSH_KEY }}
          script_stop: true
          rsync: true
          source: ".next/standalone/ public/ package.json"
          target: "/var/www/nextjs1-staging"
          args: "-avz --delete"

      - name: Restart PM2 app
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: deploy
          key: ${{ secrets.DEPLOY_SSH_KEY }}
          script: |
            pm2 reload /var/www/ecosystems/ecosystem.config.js --only nextjs1-staging
